container_image = file:///staging/ptran5/apptainer/gitlab/isescan_v1.7.3.sif

executable = isescan.sh

ResearchDrive = pelican://chtc.wisc.edu/researchdrive/ptran5/CHTC

arguments = $(sample) $(request_cpus)

transfer_input_files = $(ResearchDrive)/StaphEpi/input/$(sample).fna
transfer_output_files = results_$(sample).tar.gz, results/$(sample).fna.sum
transfer_output_remaps = "results_$(sample).tar.gz = $(ResearchDrive)/StaphEpi/ISEScan/results_$(sample).tar.gz;results/$(sample).fna.sum=$(ResearchDrive)/StaphEpi/ISEScan/$(sample).fna.sum"

log = logs/isescan_$(sample)_$(process)_$(cluster).log
error = logs/isescan_$(sample)_$(process)_$(cluster).err
output = logs/isescan_$(sample)_$(process)_$(cluster).out

#notify_user = ptran5@wisc.edu
#notification = Complete

requirements = (HasCHTCStaging == true) && (OpSysMajorVer > 7)

# Make sure you request enough disk for the container image in addition to your other input files
request_cpus = 8
request_memory = 16GB
request_disk = 30GB 

queue sample from genome_accessions.txt
