container_image = docker://quay.io/biocontainers/isescan:1.7.3--h7b50bb2_0

executable = isescan.sh

ResearchDrive = pelican://chtc.wisc.edu/researchdrive/ptran5/CHTC

# Path to data:
#/Volumes/ptran5/CHTC/StaphEpi/input/dnaA_to_rlmH_plus_1Mbp/

arguments = $(sample) $(request_cpus)

transfer_input_files = $(ResearchDrive)/StaphEpi/input/dnaA_to_rlmH_plus_1Mbp/$(sample).fasta
transfer_output_files = results_$(sample).tar.gz, results_$(sample)/$(sample).fasta.sum, results_$(sample)/$(sample).fasta.tsv
transfer_output_remaps = "results_$(sample).tar.gz = $(ResearchDrive)/StaphEpi/ISEScan/1Mbp/results_$(sample).tar.gz; \
	results_$(sample)/$(sample).fasta.sum=$(ResearchDrive)/StaphEpi/ISEScan/1Mbp/$(sample).fasta.sum; \
	results_$(sample)/$(sample).fasta.tsv=$(ResearchDrive)/StaphEpi/ISEScan/1Mbp/$(sample).fasta.tsv"

log = logs/isescan_$(sample)_$(process)_$(cluster).log
error = logs/isescan_$(sample)_$(process)_$(cluster).err
output = logs/isescan_$(sample)_$(process)_$(cluster).out

#notify_user = ptran5@wisc.edu
#notification = Complete

requirements = (HasCHTCStaging == true) && (OpSysMajorVer > 7)

# Make sure you request enough disk for the container image in addition to your other input files
request_cpus = 8
request_memory = 16GB
request_disk = 30GB 

queue sample from samples.txt
